/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

/**
 *
 * @author Aluno
 */
public class impostoR extends javax.swing.JFrame {

    /**
     * Creates new form aluguel
     */
    public impostoR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        mesesA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        display_text = new javax.swing.JLabel();
        button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("digite o valor do imposto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 129, 140, 30));

        jLabel2.setText("digite os meses em atraso");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, -1));

        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 160, -1));
        getContentPane().add(mesesA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 160, -1));

        jLabel3.setText("imposto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 190, 70));
        getContentPane().add(display_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, 170));

        button.setText("calcular");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        double valorImposto = Integer.parseInt(valor.getText());
        double mesesAtraso = Integer.parseInt(mesesA.getText());
        double percentualMulta = 0.0;
        double multaMensal;
        double multaTotal;
        
        if (valorImposto <= 500.00) {
            percentualMulta = 1.0;
        } else if (valorImposto <= 1800.00) {
            percentualMulta = 2.0;
        } else if (valorImposto <= 5000.00) {
            percentualMulta = 4.0;
        } else if (valorImposto <= 12000.00) {
            percentualMulta = 7.0;
        } else {
            percentualMulta = 10.0;
        }

        multaMensal = valorImposto * percentualMulta / 100;
        multaTotal = multaMensal * mesesAtraso;
        
        display_text.setText("Valor do imposto: R$ " + valorImposto);
        display_text.setText("Número de meses em atraso: " + mesesAtraso);
        display_text.setText("Percentual da multa: " + percentualMulta);
        display_text.setText("Valor da multa por mês: R$" + multaMensal);
        display_text.setText("Valor total da multa: R$" + multaTotal);

        display_text.requestFocus();

    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(impostoR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(impostoR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(impostoR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(impostoR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new impostoR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel display_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mesesA;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
