/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author aluno
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fatoracao = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        xadrez = new javax.swing.JLabel();
        imposto = new javax.swing.JLabel();
        romanos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fatoracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fatoracaoMouseClicked(evt);
            }
        });
        getContentPane().add(fatoracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 160));

        saldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saldoMouseClicked(evt);
            }
        });
        getContentPane().add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 180, 160));

        xadrez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xadrez.jpg"))); // NOI18N
        xadrez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xadrezMouseClicked(evt);
            }
        });
        getContentPane().add(xadrez, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 190, 160));

        imposto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imposto.jpeg"))); // NOI18N
        imposto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                impostoMouseClicked(evt);
            }
        });
        getContentPane().add(imposto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 170, 110));

        romanos.setText("romanos");
        romanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                romanosMouseClicked(evt);
            }
        });
        getContentPane().add(romanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 90, 60));

        jLabel1.setText("binarios");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ImageIcon imagem = new  ImageIcon(this.getClass().getResource("/image/saldo.jpg"));       
        Image imag = imagem.getImage().getScaledInstance(saldo.getWidth(), saldo.getHeight(), Image.SCALE_DEFAULT); 
        saldo.setIcon(new ImageIcon(imag));
        imagem = new  ImageIcon(this.getClass().getResource("/image/xadrez.jpg"));       
        Image imag2 = imagem.getImage().getScaledInstance(xadrez.getWidth(), xadrez.getHeight(), Image.SCALE_DEFAULT); 
        xadrez.setIcon(new ImageIcon(imag2));
        imagem = new  ImageIcon(this.getClass().getResource("/image/fatoração.png"));       
        Image imag3 = imagem.getImage().getScaledInstance(fatoracao.getWidth(), fatoracao.getHeight(), Image.SCALE_DEFAULT); 
        fatoracao.setIcon(new ImageIcon(imag3));
        imagem = new  ImageIcon(this.getClass().getResource("/image/imposto.jpeg"));       
        Image imag4 = imagem.getImage().getScaledInstance(imposto.getWidth(), imposto.getHeight(), Image.SCALE_DEFAULT); 
        imposto.setIcon(new ImageIcon(imag4));
    }//GEN-LAST:event_formWindowOpened

    private void xadrezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xadrezMouseClicked
        xadrez tela = new xadrez();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_xadrezMouseClicked

    private void fatoracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fatoracaoMouseClicked
        fatorial tela = new fatorial();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fatoracaoMouseClicked

    private void saldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saldoMouseClicked
        saldo_bancario tela = new saldo_bancario();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saldoMouseClicked

    private void impostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_impostoMouseClicked
        impostoR tela = new impostoR();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_impostoMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void romanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romanosMouseClicked
        romanos tela = new romanos();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_romanosMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        binarios tela = new binarios();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fatoracao;
    private javax.swing.JLabel imposto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel romanos;
    private javax.swing.JLabel saldo;
    private javax.swing.JLabel xadrez;
    // End of variables declaration//GEN-END:variables
}
