/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

/**
 *
 * @author aluno
 */
public class xadrez extends javax.swing.JFrame {

    /**
     * Creates new form xadrez
     */
    public xadrez() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtinicial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfinal = new javax.swing.JTextField();
        display_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("xadrez horas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, 60));

        txtinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinicialActionPerformed(evt);
            }
        });
        getContentPane().add(txtinicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 130, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 153, 0));
        jLabel2.setText("começo :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 50, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 153, 0));
        jLabel3.setText("termino :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 50, -1));

        txtfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfinalActionPerformed(evt);
            }
        });
        getContentPane().add(txtfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 130, -1));

        display_text.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        display_text.setForeground(new java.awt.Color(204, 102, 0));
        display_text.setCursor(new java.awt.Cursor(java.awt.Cursor.NW_RESIZE_CURSOR));
        getContentPane().add(display_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 176, 390, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinicialActionPerformed
         double hrF = Integer.parseInt(txtfinal.getText());
         double hrI = Integer.parseInt(txtinicial.getText());
         double duracao;
         
        if (hrF >= hrI) {
            
            duracao = hrF - hrI;
        } else 
        {
            duracao = (24 - hrI) + hrF;
        }

        display_text.setText("A duração do jogo é de " + duracao + " horas.");
    


    }//GEN-LAST:event_txtinicialActionPerformed

    private void txtfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfinalActionPerformed
        double hrF = Integer.parseInt(txtfinal.getText());
        double hrI = Integer.parseInt(txtinicial.getText());
        double duracao;
         
        if (hrF >= hrI) {
            
            duracao = hrF - hrI;
        } else 
        {
            duracao = (24 - hrI) + hrF;
        }

        display_text.setText("A duração do jogo é de " + duracao + " horas.");
    }//GEN-LAST:event_txtfinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xadrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xadrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xadrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xadrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xadrez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel display_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtfinal;
    private javax.swing.JTextField txtinicial;
    // End of variables declaration//GEN-END:variables
}
