/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import java.awt.Image;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Aluno
 */
public class urna extends javax.swing.JFrame {
    int num;
    int testnum;
    JLabel[] nome;
    JLabel[] numero;
    JLabel[] partido;
    JLabel[] cargo;
 
    

    

    /**
     * Creates new form urna
     */
    public urna() {
        initComponents();
        
        String nome[]= {"mia-khalifa"+"kid-bengala"+"bolsonaro"+"lula"};
        String numero[]= {"699"+"691"+"222"+"133"};
        String partido[]= {"PDB"+"PPG"+"PL"+"PT"};
        String cargo[]= {"vereadora"+"vereador"+"presidente"+"presidente"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        number1 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        foto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nume1 = new javax.swing.JLabel();
        nume2 = new javax.swing.JLabel();
        nume3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CD1 = new javax.swing.JLabel();
        CG1 = new javax.swing.JLabel();
        corr = new javax.swing.JLabel();
        noll = new javax.swing.JLabel();
        ent = new javax.swing.JLabel();
        PD1 = new javax.swing.JLabel();
        CD2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        number1.setText("1");
        number1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number1MouseClicked(evt);
            }
        });
        getContentPane().add(number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 60, 50));

        number2.setText("2");
        number2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number2MouseClicked(evt);
            }
        });
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });
        getContentPane().add(number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 60, 50));

        number3.setText("3");
        number3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number3MouseClicked(evt);
            }
        });
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });
        getContentPane().add(number3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 60, 50));

        number4.setText("4");
        number4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number4MouseClicked(evt);
            }
        });
        getContentPane().add(number4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 60, 50));

        number5.setText("5");
        number5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number5MouseClicked(evt);
            }
        });
        getContentPane().add(number5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 60, 50));

        number6.setText("6");
        number6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number6MouseClicked(evt);
            }
        });
        getContentPane().add(number6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 60, 50));

        number7.setText("7");
        number7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number7MouseClicked(evt);
            }
        });
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });
        getContentPane().add(number7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 60, 50));

        number8.setText("8");
        number8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number8MouseClicked(evt);
            }
        });
        getContentPane().add(number8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 60, 50));

        number9.setText("9");
        number9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number9MouseClicked(evt);
            }
        });
        getContentPane().add(number9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 60, 50));

        number0.setText("0");
        number0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                number0MouseClicked(evt);
            }
        });
        getContentPane().add(number0, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 60, 50));

        foto.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 260, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Candidato:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 120, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Partido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 140, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Cargo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 80, 30));

        nume1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nume1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(nume1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 80, 70));

        nume2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nume2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(nume2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 70, 70));

        nume3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        nume3.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(nume3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 70, 70));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 100, -1));

        CD1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CD1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(CD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 210, 0));

        CG1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CG1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(CG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 200, 30));

        corr.setBackground(new java.awt.Color(255, 255, 51));
        corr.setForeground(new java.awt.Color(51, 0, 51));
        corr.setText("CORRIGE");
        corr.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        corr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corrMouseClicked(evt);
            }
        });
        getContentPane().add(corr, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        noll.setText("nulo");
        noll.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(noll, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 30, -1));

        ent.setBackground(new java.awt.Color(51, 255, 51));
        ent.setText("ENTRAR");
        ent.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        ent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entMouseClicked(evt);
            }
        });
        getContentPane().add(ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        PD1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PD1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(PD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 180, 30));

        CD2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CD2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(CD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 190, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number3ActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number7ActionPerformed

    private void number1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number1MouseClicked
        num = 1;
        testnum();
        Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number1MouseClicked

    private void number2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number2MouseClicked
        num = 2;
        testnum();
        Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number2MouseClicked

    private void number3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number3MouseClicked
       num = 3;
       testnum();
       Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number3MouseClicked

    private void number4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number4MouseClicked
        num = 4;
        testnum();
        Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number4MouseClicked

    private void number5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number5MouseClicked
       num = 5;
       testnum();
       Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number5MouseClicked

    private void number6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number6MouseClicked
        num =6;
        testnum();
        Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number6MouseClicked

    private void number7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number7MouseClicked
       num = 7;
       testnum();
       Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number7MouseClicked

    private void number8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number8MouseClicked
       num = 8;
       testnum();
       Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number8MouseClicked

    private void number9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number9MouseClicked
        num = 9;
        testnum();
        Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number9MouseClicked

    private void number0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_number0MouseClicked
        num = 0;
        testnum();
        Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\Tecla.wav");
    }//GEN-LAST:event_number0MouseClicked

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number2ActionPerformed

    private void corrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corrMouseClicked
        nume1.setText("");
        nume2.setText("");
        nume3.setText("");
        CD2.setText("");
        CG1.setText("");
        PD1.setText("");
        
        ImageIcon imagem = new ImageIcon(this.getClass().getResource(""));
        Image imag = imagem.getImage().getScaledInstance(foto.getWidth(),
         foto.getHeight(),  Image.SCALE_DEFAULT);
        foto.setIcon(new ImageIcon( imag));
        
        
    }//GEN-LAST:event_corrMouseClicked

    private void entMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entMouseClicked
       Som p = new Som();
       p.Som("D:\\Etec\\tpa\\java\\netbins projetos\\urna\\urna_eletronica\\src\\imagem\\urna.wav");
               nume1.setText("");
        nume2.setText("");
        nume3.setText("");
        CD2.setText("");
        CG1.setText("");
        PD1.setText("");
        
        ImageIcon imagem = new ImageIcon(this.getClass().getResource(""));
        Image imag = imagem.getImage().getScaledInstance(foto.getWidth(),
         foto.getHeight(),  Image.SCALE_DEFAULT);
        foto.setIcon(new ImageIcon( imag));
        
    }//GEN-LAST:event_entMouseClicked
    public class Som {
    public void Som (String soundName) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            System.out.println("Erro ao executar SOM!");
            ex.printStackTrace();
        }
    }
}
    private void testnum(){
        if(nume1.getText().equals("")){
            nume1.setText(String.valueOf(num));
            
        }
        else if(nume2.getText().equals("")){
            nume2.setText(String.valueOf(num));
            
        }
        else if(nume3.getText().equals("")){
                nume3.setText(String.valueOf(num));
                cand();
                        
                }
    }
    
    private void cand(){
         ImageIcon imagem = new ImageIcon(this.getClass().getResource("/imagem/candidato_" + nume1.getText()+nume2.getText()+nume3.getText()+".png"));
        Image imag = imagem.getImage().getScaledInstance(foto.getWidth(),
         foto.getHeight(),  Image.SCALE_DEFAULT);
        foto.setIcon(new ImageIcon( imag));
        
        
        for(int x = 0; x < 4; x++) {
            String numes = nume1.getText() + nume2.getText() + nume3.getText();
            if(numes.equals("222")){
                CD2.setText("bolsonaro");
                PD1.setText("PL");
                CG1.setText("predisidente");
            }
            else if(numes.equals("133")){
                CD2.setText("lula");
                PD1.setText("PT");
                CG1.setText("predisidente");
            }
            else if(numes.equals("691")){
                CD2.setText("kid_begala");
                PD1.setText("PPG");
                CG1.setText("vereador");
            }
            else if(numes.equals("699")){
                CD2.setText("Mia_khalifa");
                PD1.setText("PDB");
                CG1.setText("vereadora");
        
        }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new urna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CD1;
    private javax.swing.JLabel CD2;
    private javax.swing.JLabel CG1;
    private javax.swing.JLabel PD1;
    private javax.swing.JLabel corr;
    private javax.swing.JLabel ent;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel noll;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JLabel nume1;
    private javax.swing.JLabel nume2;
    private javax.swing.JLabel nume3;
    // End of variables declaration//GEN-END:variables
}
